export type StepType =
  | 'consulta'
  | 'antecedentes'
  | 'alergias'
  | 'farmacos'
  | 'inicioCuadro'
  | 'evolucion'
  | 'localizacion'
  | 'caracteristicas'
  | 'sintomasAsociados'
  | 'factoresDesencadenantes'
  | 'antecedentesRecientes'
  | 'repercusiones'
  | 'tratamientosPrevios'
  | 'sintomasAlarma'
  | 'resumen';
